### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by newor0599** [Sloimayyy/mcschematic#4]
I made a test code, but i cant seem to run it
Here is the code:

```
import mcschematic
s = mcschematic.MCSchematic()
w=10
h=10
s.setBlock((0,0,0),"minecraft:white_concreate")
s.save("/home/newor/.minecraft/config/worldedit/schematics","test",mcschematic.Version.JE_1_20_1)

```

And i got an error:

```
Traceback (most recent call last):
  File "/home/newor/code/python/mc video player/video player mc.py", line 1, in <module>
    import mcschematic
  File "/home/newor/.local/lib/python3.8/site-packages/mcschematic/__init__.py", line 1, in <module>
    from .mcschematic import *
  File "/home/newor/.local/lib/python3.8/site-packages/mcschematic/mcschematic.py", line 408, in <module>
    class MCBlockStateManipulator:
  File "/home/newor/.local/lib/python3.8/site-packages/mcschematic/mcschematic.py", line 414, in MCBlockStateManipulator
    _horizontalFacingPropertyRotationList: list[str] = ["north", "east", "south", "west"]
TypeError: 'type' object is not subscriptable
```

**Comment by Sloimayyy** [comment]
MCSchematic is a python 3.9+ package.
It was written on the Pypi page of the package but not here in the readme so I added it here too!

**Comment by newor0599** [comment]
Thanks for the quick reply :D

**Comment by Sloimayyy** [comment]
My pleasure :)
